version: "3.7"

services:
  router1:
    build: ./Router
    entrypoint: ["iex", "--sname", "router@router1", "--cookie", "useasecurepasswordhere", "-S", "mix"]
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - router1

  server1:
    build: ./Server
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 5 && iex "--sname" "server@server1" "--cookie" "useasecurepasswordhere" "-S" "mix"'
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - server1
    depends_on:
      - router1        

  usuario1:
    build: ./Cliente
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 5 && iex "--sname" "usuario1@usuario1" "--cookie" "useasecurepasswordhere" "-S" "mix"'
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - usuario1
    depends_on:
      - router1
      - server1

  usuario2:
    build: ./Cliente
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 5 && iex "--sname" "usuario2@usuario2" "--cookie" "useasecurepasswordhere" "-S" "mix"'
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - usuario2
    depends_on:
      - router1
      - server1

networks:
  iasc-network:
    driver: bridge
