version: "3.7"

services:
  router:
    build: ./Router
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - router

  server:
    build: ./Server
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - server
    depends_on:
      - router
      
  usuario:
    build: ./Cliente
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - usuario
    depends_on:
      - server

networks:
  iasc-network:
    driver: bridge
