version: "3.7"

services:
  router1:
    build: ./Router
    entrypoint: ["iex", "--sname", "router@router1", "--cookie", "useasecurepasswordhere", "--erl",  "-config config/router-1", "-S", "mix"]
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - router1

  router2:
    build: ./Router
    entrypoint: ["iex", "--sname", "router@router2", "--cookie", "useasecurepasswordhere", "--erl",  "-config config/router-2", "-S", "mix"]
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - router2

  router3:
    build: ./Router
    entrypoint: ["iex", "--sname", "router@router3", "--cookie", "useasecurepasswordhere", "--erl",  "-config config/router-3", "-S", "mix"]
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - router3

  server1:
    build: ./Server
    command:
      - '/bin/sh'
      - '-c'
      - 'sleep 10 && iex "--sname" "server@server1" "--cookie" "useasecurepasswordhere" "-S" "mix"'
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - server1

  server2:
    build: ./Server
    command:
      - '/bin/sh'
      - '-c'
      - 'sleep 10 && iex "--sname" "server@server2" "--cookie" "useasecurepasswordhere" "-S" "mix"'
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - server2

  server3:
    build: ./Server
    command:
      - '/bin/sh'
      - '-c'
      - 'sleep 10 && iex "--sname" "server@server3" "--cookie" "useasecurepasswordhere" "-S" "mix"'
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - server3

  usuario1:
    build: ./Cliente
    command:
      - '/bin/sh'
      - '-c'
      - 'sleep 15 && iex "--sname" "usuario1@usuario1" "--cookie" "useasecurepasswordhere" "-S" "mix"'
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - usuario1

  usuario2:
    build: ./Cliente
    command:
      - '/bin/sh'
      - '-c'
      - 'sleep 15 && iex "--sname" "usuario2@usuario2" "--cookie" "useasecurepasswordhere" "-S" "mix"'
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - usuario2

  usuario3:
    build: ./Cliente
    command:
      - '/bin/sh'
      - '-c'
      - 'sleep 15 && iex "--sname" "usuario3@usuario3" "--cookie" "useasecurepasswordhere" "-S" "mix"'
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - usuario3

networks:
  iasc-network:
    driver: bridge
