version: "3.7"

services:
  router1:
    build: ./Router
    image: iasc/router
    entrypoint: ["iex", "--sname", "router@router1", "--cookie", "useasecurepasswordhere", "--erl",  "-config config/router-1", "-S", "mix"]
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - router1
          
  router2:
    build: ./Router
    image: iasc/router
    entrypoint: ["iex", "--sname", "router@router2", "--cookie", "useasecurepasswordhere", "--erl",  "-config config/router-2", "-S", "mix"]
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - router2

  router3:
    build: ./Router
    image: iasc/router
    entrypoint: ["iex", "--sname", "router@router3", "--cookie", "useasecurepasswordhere", "--erl",  "-config config/router-3", "-S", "mix"]
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - router3

  server1:
    build: ./Server
    image: iasc/server
    command:
      - '/bin/sh'
      - '-c'
      - '/app/wait-for-it.sh router1:4369 && /app/wait-for-it.sh router2:4369 && /app/wait-for-it.sh router3:4369 && sleep 5 && iex "--sname" "server@server1" "--cookie" "useasecurepasswordhere" "-S" "mix"'
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - server1

  usuario1:
    build: ./Cliente
    image: iasc/cliente
    command:
      - '/bin/sh'
      - '-c'
      - '/app/wait-for-it.sh server1:4369 && sleep 10 && iex "--sname" "usuario1@usuario1" "--cookie" "useasecurepasswordhere" "-S" "mix"'
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - usuario1

  usuario2:
    build: ./Cliente
    image: iasc/cliente
    command:
      - '/bin/sh'
      - '-c'
      - '/app/wait-for-it.sh server1:4369 && sleep 10 && iex "--sname" "usuario2@usuario2" "--cookie" "useasecurepasswordhere" "-S" "mix"'
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - usuario2
      
  usuario3:
    build: ./Cliente
    image: iasc/cliente
    command:
      - '/bin/sh'
      - '-c'
      - '/app/wait-for-it.sh server1:4369 && sleep 10 && iex "--sname" "usuario3@usuario3" "--cookie" "useasecurepasswordhere" "-S" "mix"'
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - usuario3

networks:
  iasc-network:
    driver: bridge
