version: "3.7"

services:
  router1:
    build: ./Router
    entrypoint: ["iex", "--sname", "Router1@router1", "--cookie", "useasecurepasswordhere", "-S", "mix"]
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - router1

  router2:
    build: ./Router
    entrypoint: ["iex", "--sname", "Router2@router2", "--cookie", "useasecurepasswordhere", "-S", "mix"]
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - router2

  router3:
    build: ./Router
    entrypoint: ["iex", "--sname", "Router3@router3", "--cookie", "useasecurepasswordhere", "-S", "mix"]
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - router3

  server1:
    build: ./Server
    command:
      - '/bin/sh'
      - '-c'
      - '/app/wait-for-it.sh router1:4369 && /app/wait-for-it.sh router2:4369 && /app/wait-for-it.sh router3:4369 && sleep 10 && iex "--sname" "server@server1" "--cookie" "useasecurepasswordhere" "-S" "mix"'
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - server1

  server2:
    build: ./Server
    command:
      - '/bin/sh'
      - '-c'
      - '/app/wait-for-it.sh router1:4369 && /app/wait-for-it.sh router2:4369 && /app/wait-for-it.sh router3:4369 && sleep 12 && iex "--sname" "server@server2" "--cookie" "useasecurepasswordhere" "-S" "mix"'
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - server2

  server3:
    build: ./Server
    command:
      - '/bin/sh'
      - '-c'
      - '/app/wait-for-it.sh router1:4369 && /app/wait-for-it.sh router2:4369 && /app/wait-for-it.sh router3:4369 && sleep 14 && iex "--sname" "server@server3" "--cookie" "useasecurepasswordhere" "-S" "mix"'
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - server3

  usuario1:
    build: ./Cliente
    command:
      - '/bin/sh'
      - '-c'
      - '/app/wait-for-it.sh router1:4369 && /app/wait-for-it.sh router2:4369 && /app/wait-for-it.sh router3:4369 && /app/wait-for-it.sh server1:4369 && /app/wait-for-it.sh server2:4369 && /app/wait-for-it.sh server3:4369 && sleep 16 && iex "--sname" "usuario1@usuario1" "--cookie" "useasecurepasswordhere" "-S" "mix"'
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - usuario1

  usuario2:
    build: ./Cliente
    command:
      - '/bin/sh'
      - '-c'
      - '/app/wait-for-it.sh router1:4369 && /app/wait-for-it.sh router2:4369 && /app/wait-for-it.sh router3:4369 && /app/wait-for-it.sh server1:4369 && /app/wait-for-it.sh server2:4369 && /app/wait-for-it.sh server3:4369 && sleep 18 && iex "--sname" "usuario2@usuario2" "--cookie" "useasecurepasswordhere" "-S" "mix"'
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - usuario2

  usuario3:
    build: ./Cliente
    command:
      - '/bin/sh'
      - '-c'
      - '/app/wait-for-it.sh router1:4369 && /app/wait-for-it.sh router2:4369 && /app/wait-for-it.sh router3:4369 && /app/wait-for-it.sh server1:4369 && /app/wait-for-it.sh server2:4369 && /app/wait-for-it.sh server3:4369 && sleep 20 && iex "--sname" "usuario3@usuario3" "--cookie" "useasecurepasswordhere" "-S" "mix"'
    stdin_open: true
    tty: true
    networks:
      iasc-network:
        aliases:
          - usuario3

networks:
  iasc-network:
    driver: bridge
